REM *** UKSTRVS03 ***

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS03-N$-PUK_Vol1-BAR.jpg" "\\ukstrvs03\VS03_VOL01"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS03-R$-PUK_Vol2-BAR.jpg" "\\ukstrvs03\VS03_VOL02"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS03-P$-PUK_Vol3-BAR.jpg" "\\ukstrvs03\VS03_VOL03"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS03-Z$-PUK_Vol4-BAR.jpg" "\\ukstrvs03\VS03_VOL04"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS03-Z$-PUK_Vol5-BAR.jpg" "\\ukstrvs03\VS03_VOL05"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS03-Z$-PUK_Vol6-BAR.jpg" "\\ukstrvs03\VS03_VOL06"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS03-N$-PUK_Vol7-BAR.jpg" "\\ukstrvs03\VS03_VOL07"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS03-O$-PUK_Vol8-BAR.jpg" "\\ukstrvs03\VS03_VOL08"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS03-O$-PUK_Vol9-BAR.jpg" "\\ukstrvs03\VS03_VOL09"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS03-R$-PUK_Vol10-BAR.jpg" "\\ukstrvs03\VS03_VOL10"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS03-N$-PUK_Vol1-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS03-N$-PUK_Vol1-BAR.xml" "\\ukstrvs03\VS03_VOL01"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS03-R$-PUK_Vol2-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS03-R$-PUK_Vol2-BAR.xml" "\\ukstrvs03\VS03_VOL02"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS03-P$-PUK_Vol3-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS03-P$-PUK_Vol3-BAR.xml" "\\ukstrvs03\VS03_VOL03"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS03-Z$-PUK_Vol4-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS03-Z$-PUK_Vol4-BAR.xml" "\\ukstrvs03\VS03_VOL04"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS03-Z$-PUK_Vol5-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS03-Z$-PUK_Vol5-BAR.xml" "\\ukstrvs03\VS03_VOL05"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS03-Z$-PUK_Vol6-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS03-Z$-PUK_Vol6-BAR.xml" "\\ukstrvs03\VS03_VOL06"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS03-N$-PUK_Vol7-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS03-N$-PUK_Vol7-BAR.xml" "\\ukstrvs03\VS03_VOL07"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS03-O$-PUK_Vol8-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS03-O$-PUK_Vol8-BAR.xml" "\\ukstrvs03\VS03_VOL08"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS03-O$-PUK_Vol9-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS03-O$-PUK_Vol9-BAR.xml" "\\ukstrvs03\VS03_VOL09"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS03-R$-PUK_Vol10-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS03-R$-PUK_Vol10-BAR.xml" "\\ukstrvs03\VS03_VOL10"

REM *** UKSTRVS04 ***

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS04-X$-DK_Hi_Res_Archive-BAR.jpg" "\\ukstrvs04\DK Hi-Res Archive"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS04-L$-DK_Hi_Res_Archive2-BAR.jpg" "\\ukstrvs04\DK Hi-Res Archive2"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS04-K$-DK_Hi_Res_Archive3-BAR.jpg" "\\ukstrvs04\DK Hi-Res Archive3"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS04-J$-DK_Hi_Res_Archive4-BAR.jpg" "\\ukstrvs04\DK Hi-Res Archive4"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS04-Y$-DK_Hi_Res_Archive5-BAR.jpg" "\\ukstrvs04\DK Hi-Res Archive5"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS04-X$-DK_Hi_Res_Archive-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS04-X$-DK_Hi_Res_Archive-BAR.xml" "\\ukstrvs04\DK Hi-Res Archive"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS04-L$-DK_Hi_Res_Archive2-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS04-L$-DK_Hi_Res_Archive2-BAR.xml" "\\ukstrvs04\DK Hi-Res Archive2"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS04-K$-DK_Hi_Res_Archive3-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS04-K$-DK_Hi_Res_Archive3-BAR.xml" "\\ukstrvs04\DK Hi-Res Archive3"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS04-J$-DK_Hi_Res_Archive4-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS04-J$-DK_Hi_Res_Archive4-BAR.xml" "\\ukstrvs04\DK Hi-Res Archive4"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS04-Y$-DK_Hi_Res_Archive5-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS04-Y$-DK_Hi_Res_Archive5-BAR.xml" "\\ukstrvs04\DK Hi-Res Archive5"

REM *** UKSTRVS05 ***

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS05-U$-Vol02-BAR.jpg" "\\ukstrvs05\VS05_VOL02"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS05-T$-Vol04-BAR.jpg" "\\ukstrvs05\VS05_VOL04"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS05-W$-Vol05-BAR.jpg" "\\ukstrvs05\VS05_VOL05"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS05-W$-Vol07-BAR.jpg" "\\ukstrvs05\VS05_VOL07"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS05-W$-Vol08-BAR.jpg" "\\ukstrvs05\VS05_VOL08"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS05-V$-Vol09-BAR.jpg" "\\ukstrvs05\VS05_VOL09"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS05-S$-Vol11-BAR.jpg" "\\ukstrvs05\VS05_VOL11"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS05-U$-Vol02-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS05-U$-Vol02-BAR.xml" "\\ukstrvs05\VS05_VOL02"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS05-T$-Vol04-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS05-T$-Vol04-BAR.xml" "\\ukstrvs05\VS05_VOL04"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS05-W$-Vol05-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS05-W$-Vol05-BAR.xml" "\\ukstrvs05\VS05_VOL05"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS05-W$-Vol07-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS05-W$-Vol07-BAR.xml" "\\ukstrvs05\VS05_VOL07"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS05-W$-Vol08-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS05-W$-Vol08-BAR.xml" "\\ukstrvs05\VS05_VOL08"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS05-V$-Vol09-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS05-V$-Vol09-BAR.xml" "\\ukstrvs05\VS05_VOL09"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS05-S$-Vol11-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS05-S$-Vol11-BAR.xml" "\\ukstrvs05\VS05_VOL11"

REM *** UKSTRVS06 ***

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS06-X$-DK_Hi_Res_Archive-BAR.jpg" "\\ukstrvs06\DK Hi-Res Archive"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS06-K$-DK_Hi_Res_Archive3-BAR.jpg" "\\ukstrvs06\DK Hi-Res Archive3"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS06-J$-DK_Hi_Res_Archive4-BAR.jpg" "\\ukstrvs06\DK Hi-Res Archive4"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS06-Y$-DK_Hi_Res_Archive5-BAR.jpg" "\\ukstrvs06\DK Hi-Res Archive5"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS06-M$-MacSupport-BAR.jpg" "\\ukstrvs06\MacSupport"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS06-M$-Rough_Guides_Digital-BAR.jpg" "\\ukstrvs06\Rough Guides Digital"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS06-X$-DK_Hi_Res_Archive-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS06-X$-DK_Hi_Res_Archive-BAR.xml" "\\ukstrvs06\DK Hi-Res Archive"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS06-K$-DK_Hi_Res_Archive3-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS06-K$-DK_Hi_Res_Archive3-BAR.xml" "\\ukstrvs06\DK Hi-Res Archive3"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS06-J$-DK_Hi_Res_Archive4-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS06-J$-DK_Hi_Res_Archive4-BAR.xml" "\\ukstrvs06\DK Hi-Res Archive4"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS06-Y$-DK_Hi_Res_Archive5-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS06-Y$-DK_Hi_Res_Archive5-BAR.xml" "\\ukstrvs06\DK Hi-Res Archive5"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS06-M$-MacSupport-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS06-M$-MacSupport-BAR.xml" "\\ukstrvs06\MacSupport"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS06-M$-Rough_Guides_Digital-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS06-M$-Rough_Guides_Digital-BAR.xml" "\\ukstrvs06\Rough Guides Digital"

REM *** UKSTRVS07 ***

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS07-E$-Vol01-BAR.jpg" "\\ukstrvs07\VS07_VOL01"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS07-F$-Vol02-BAR.jpg" "\\ukstrvs07\VS07_VOL02"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS07-G$-Vol03-BAR.jpg" "\\ukstrvs07\VS07_VOL03"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS07-H$-Vol04-BAR.jpg" "\\ukstrvs07\VS07_VOL04"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS07-I$-Vol05-BAR.jpg" "\\ukstrvs07\VS07_VOL05"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS07-E$-Vol01-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS07-E$-Vol01-BAR.xml" "\\ukstrvs07\VS07_VOL01"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS07-F$-Vol02-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS07-F$-Vol02-BAR.xml" "\\ukstrvs07\VS07_VOL02"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS07-G$-Vol03-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS07-G$-Vol03-BAR.xml" "\\ukstrvs07\VS07_VOL03"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS07-H$-Vol04-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS07-H$-Vol04-BAR.xml" "\\ukstrvs07\VS07_VOL04"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS07-I$-Vol05-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS07-I$-Vol05-BAR.xml" "\\ukstrvs07\VS07_VOL05"

REM *** UKSTRFS01 ***

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\FS01-E$-BBCA-BAR.jpg" "\\ukstrfs01\BBC Archive"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\FS01-F$-PreSchool_Archive-BAR.jpg" "\\ukstrfs01\Preschool Archive"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\FS01-E$-BBCA-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\FS01-E$-BBCA-BAR.xml" "\\ukstrfs01\BBC Archive"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\FS01-F$-PreSchool_Archive-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\FS01-F$-PreSchool_Archive-BAR.xml" "\\ukstrfs01\PreSchool Archive"

REM *** UKSTRFS04 ***

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\FS04-Q$-BBC-BAR.jpg" "\\ukstrfs04\BBC"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\FS04-Q$-Publishing_Management-BAR.jpg" "\\ukstrfs04\Publishing Management"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\FS04-Q$-Warne_Resources-BAR.jpg" "\\ukstrfs04\Warne Resources"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\FS04-R$-B&L_Resources-BAR.jpg" "\\ukstrfs04\B&L Resources"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\FS04-S$-0-8-BAR.jpg" "\\ukstrfs04\0-8"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\FS04-S$-Licensing-BAR.jpg" "\\ukstrfs04\Licensing"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\FS04-T$-VolA01-BAR.jpg" "\\ukstrfs04\VolA01"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\FS04-U$-VolA02-BAR.jpg" "\\ukstrfs04\VolA02"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\FS04-V$-VolA03-BAR.jpg" "\\ukstrfs04\VolA03"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\FS04-X$-VolA04-BAR.jpg" "\\ukstrfs04\VolA04"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\FS04-Y$-VolA05-BAR.jpg" "\\ukstrfs04\VolA05"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\FS04-Q$-BBC-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\FS04-Q$-BBC.xml" "\\ukstrfs04\BBC"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\FS04-Q$-Publishing_Management-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\FS04-Q$-Publishing_Management-BAR.xml" "\\ukstrfs04\Publishing Management"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\FS04-Q$-Warne_Resources-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\FS04-Q$-Warne_Resources-BAR.xml" "\\ukstrfs04\Warne Resources"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\FS04-R$-B&L_Resources-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\FS04-R$-B&L_Resources-BAR.xml" "\\ukstrfs04\B&L Resources"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\FS04-S$-0-8-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\FS04-S$-0-8-BAR.xml" "\\ukstrfs04\0-8"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\FS04-S$-Licensing-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\FS04-S$-Licensing-BAR.xml" "\\ukstrfs04\Licensing"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\FS04-T$-VolA01-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\FS04-T$-VolA01-BAR.xml" "\\ukstrfs04\VolA01"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\FS04-U$-VolA02-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\FS04-U$-VolA02-BAR.xml" "\\ukstrfs04\VolA02"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\FS04-V$-VolA03-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\FS04-V$-VolA03-BAR.xml" "\\ukstrfs04\VolA03"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\FS04-X$-VolA04-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\FS04-X$-VolA04-BAR.xml" "\\ukstrfs04\VolA04"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\FS04-Y$-VolA05-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\FS04-Y$-VolA05-BAR.xml" "\\ukstrfs04\VolA05"

REM *** UKSTRFS05 ***

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\FS05-E$-DK_Child._HiRes_Image-BAR.jpg" "\\ukstrfs05\DK-Childrens HiRes Img Temp"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\FS05-E$-DK_Life._HiRes_Image-BAR.jpg" "\\ukstrfs05\DK-Lifestyle HiRes Img Temp"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\FS05-E$-DK_Reference_HiRes_Image-BAR.jpg" "\\ukstrfs05\DK-Reference HiRes Img Temp"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\FS05-E$-Penguin_HiRes_Image-BAR.jpg" "\\ukstrfs05\Penguin HiRes Img Temp"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\FS05-F$-DK_Archive-BAR.jpg" "\\ukstrfs05\DK Archive"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\FS05-F$-Penguin_Audio_Books-BAR.jpg" "\\ukstrfs05\Penguin Audio Books"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\FS05-F$-Penguin_Backlist_Conversion-BAR.jpg" "\\ukstrfs05\Penguin Backlist Conversion Source Files$"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\FS05-F$-Production_Transfer-BAR.jpg" "\\ukstrfs05\Production Transfer"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\FS05-F$-Puffin_Archive-BAR.jpg" "\\ukstrfs05\Puffin Archive"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\FS05-G$-BBCA_Video_Archive-BAR.jpg" "\\ukstrfs05\BBC Active Video Archive"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\FS05-G$-DK_Travel_HiRes_Img_Temp-BAR.jpg" "\\ukstrfs05\DK Travel HiRes Img Temp"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\FS05-E$-DK_Child._HiRes_Image-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\FS05-E$-DK_Child._HiRes_Image-BAR.xml" "\\ukstrfs05\DK-Childrens HiRes Img Temp"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\FS05-E$-DK_Life._HiRes_Image-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\FS05-E$-DK_Life._HiRes_Image-BAR.xml" "\\ukstrfs05\DK-Lifestyle HiRes Img Temp"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\FS05-E$-DK_Reference_HiRes_Image-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\FS05-E$-DK_Reference_HiRes_Image-BAR.xml" "\\ukstrfs05\DK-Reference HiRes Img Temp"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\FS05-F$-DK_Archive-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\FS05-F$-DK_Archive-BAR.xml" "\\ukstrfs05\DK Archive"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\FS05-F$-Penguin_Audio_Books-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\FS05-F$-Penguin_Audio_Books-BAR.xml" "\\ukstrfs05\Penguin Audio Books"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\FS05-F$-Penguin_Backlist_Conversion-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\FS05-F$-Penguin_Backlist_Conversion-BAR.xml" "\\ukstrfs05\Penguin Backlist Conversion Source Files$"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\FS05-F$-Production_Transfer-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\FS05-F$-Production_Transfer-BAR.xml" "\\ukstrfs05\Production Transfer"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\FS05-F$-Puffin_Archive-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\FS05-F$-Puffin_Archive-BAR.xml" "\\ukstrfs05\Puffin Archive"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\FS05-G$-BBCA_Video_Archive-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\FS05-G$-BBCA_Video_Archive-BAR.xml" "\\ukstrfs05\BBC Active Video Archive"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\FS05-G$-DK_Travel_HiRes_Img_Temp-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\FS05-G$-DK_Travel_HiRes_Img_Temp-BAR.xml" "\\ukstrfs05\DK Travel HiRes Img Temp"
