REM *** Need to remove these files as it will create a new worktab in the spreadsheet which results in an incorrect report.

del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-G$-PUK.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-I$-PUK-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-J$-PUK-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-K$-PUK-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-L$-PED_KB-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-L$-PSS-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-L$-PUK-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-M$-PUK-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-M$-GEN_ED2-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-M$-PUK_PROGRAMS-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-P$-PED-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-P$-PSS-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-P$-PUK-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-S$-PUK_DIGITAL_CONTENT-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-T$-PED_PAS-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-W$-PUK_MAC-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-X$-PED_BBCA-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-Y$-PLC-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-Y$-PUK-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS02-PUK_ATOM-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS02-PUK_NTOZ-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS02-NONPUK-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS02-PSSUSERS-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS03-N$-PUK_Vol1-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS03-R$-PUK_Vol2-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS03-P$-PUK_Vol3-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS03-Z$-PUK_Vol4-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS03-Z$-PUK_Vol5-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS03-Z$-PUK_Vol6-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS03-N$-PUK_Vol7-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS03-O$-PUK_Vol8-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS03-O$-PUK_Vol9-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS03-R$-PUK_Vol10-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS04-X$-DK_Hi_Res_Archive-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS04-L$-DK_Hi_Res_Archive2-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS04-K$-DK_Hi_Res_Archive3-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS04-J$-DK_Hi_Res_Archive4-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS04-Y$-DK_Hi_Res_Archive5-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS05-U$-Vol02-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS05-T$-Vol04-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS05-W$-Vol05-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS05-W$-Vol07-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS05-V$-Vol09-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS05-S$-Vol11-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS06-X$-DK_Hi_Res_Archive-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS06-K$-DK_Hi_Res_Archive3-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS06-J$-DK_Hi_Res_Archive4-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS06-Y$-DK_Hi_Res_Archive5-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS06-M$-MacSupport-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS06-M$-Rough_Guides_Digital-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS07-E$-Vol01-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS07-F$-Vol02-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS07-G$-Vol03-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS07-H$-Vol04-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS07-I$-Vol05-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\FS04-Q$-BBC-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\FS04-Q$-Publishing_Management-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\FS04-Q$-Warne_Resources-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\FS04-R$-B&L_Resources-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\FS04-S$-0-8-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\FS04-S$-Licensing-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\FS04-T$-VolA01-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\FS04-U$-VolA02-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\FS04-V$-VolA03-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\FS04-X$-VolA04-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\FS04-Y$-VolA05-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS05-S$-Vol13-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS06-L$-DK_Hi_Res_Archive2-BAR.xls"
del "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\FS05-F$-Penguin_Archive-BAR.xls"

REM *** UKSTRVS01 & UKSTRVS02 ***
"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-G$-PUK.xls" "\\ukstrvs01\g$\pss programs"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-I$-PUK-BAR.xls" "\\ukstrvs01\PUK DATA8"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-J$-PUK-BAR.xls" "\\ukstrvs01\PUK DATA6"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-K$-PUK-BAR.xls" "\\ukstrvs01\PUK DATA5"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-L$-PED_KB-BAR.xls" "\\ukstrvs01\KNOWLEDGE BOX$"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-L$-PSS-BAR.xls" "\\ukstrvs01\PSS DATA4"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-L$-PUK-BAR.xls" "\\ukstrvs01\PUK DATA7"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-M$-PUK-BAR.xls" "\\ukstrvs01\PUK DATA3$"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-M$-GEN_ED2-BAR.xls" "\\ukstrvs01\GEN ED2$"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-M$-PUK_PROGRAMS-BAR.xls" "\\ukstrvs01\PUK PROGRAMS"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-P$-PED-BAR.xls" "\\ukstrvs01\PED DATA2"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-P$-PSS-BAR.xls" "\\ukstrvs01\PSS DATA2"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-P$-PUK-BAR.xls" "\\ukstrvs01\PUK DATA2"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-S$-PUK_DIGITAL_CONTENT-BAR.xls" "\\ukstrvs01\DIGITAL CONTENT$"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-T$-PED_PAS-BAR.xls" "\\ukstrvs01\PAS DATA"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-W$-PUK_MAC-BAR.xls" "\\ukstrvs01\W$\PUK MAC"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-X$-PED_BBCA-BAR.xls" "\\ukstrvs01\X$\PED DATA"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-Y$-PLC-BAR.xls" "\\ukstrvs01\PLC DATA"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS01-Y$-PUK-BAR.xls" "\\ukstrvs01\PUK DATA"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS02-PUK_ATOM-BAR.xls" "\\ukstrvs02\USERSPUKATOM"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS02-PUK_NTOZ-BAR.xls" "\\ukstrvs02\USERSPUKNTOZ"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS02-NONPUK-BAR.xls" "\\ukstrvs02\USERSNONPUK"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS02-PSSUSERS-BAR.xls" "\\ukstrvs02\USERSPSS"

REM *** UKSTRVS03 ***

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS03-N$-PUK_Vol1-BAR.xls" "\\ukstrvs03\VS03_VOL01"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS03-R$-PUK_Vol2-BAR.xls" "\\ukstrvs03\VS03_VOL02"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS03-P$-PUK_Vol3-BAR.xls" "\\ukstrvs03\VS03_VOL03"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS03-Z$-PUK_Vol4-BAR.xls" "\\ukstrvs03\VS03_VOL04"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS03-Z$-PUK_Vol5-BAR.xls" "\\ukstrvs03\VS03_VOL05"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS03-Z$-PUK_Vol6-BAR.xls" "\\ukstrvs03\VS03_VOL06"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS03-N$-PUK_Vol7-BAR.xls" "\\ukstrvs03\VS03_VOL07"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS03-O$-PUK_Vol8-BAR.xls" "\\ukstrvs03\VS03_VOL08"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS03-O$-PUK_Vol9-BAR.xls" "\\ukstrvs03\VS03_VOL09"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS03-R$-PUK_Vol10-BAR.xls" "\\ukstrvs03\VS03_VOL10"

REM *** UKSTRVS04 ***

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS04-X$-DK_Hi_Res_Archive-BAR.xls" "\\ukstrvs04\DK Hi-Res Archive"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS04-L$-DK_Hi_Res_Archive2-BAR.xls" "\\ukstrvs04\DK Hi-Res Archive2"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS04-K$-DK_Hi_Res_Archive3-BAR.xls" "\\ukstrvs04\DK Hi-Res Archive3"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS04-J$-DK_Hi_Res_Archive4-BAR.xls" "\\ukstrvs04\DK Hi-Res Archive4"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS04-Y$-DK_Hi_Res_Archive5-BAR.xls" "\\ukstrvs04\DK Hi-Res Archive5"

REM *** UKSTRVS05 ***

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS05-U$-Vol02-BAR.xls" "\\ukstrvs05\VS05_VOL02"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS05-T$-Vol04-BAR.xls" "\\ukstrvs05\VS05_VOL04"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS05-W$-Vol05-BAR.xls" "\\ukstrvs05\VS05_VOL05"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS05-W$-Vol07-BAR.xls" "\\ukstrvs05\VS05_VOL07"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS05-V$-Vol09-BAR.xls" "\\ukstrvs05\VS05_VOL09"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS05-S$-Vol11-BAR.xls" "\\ukstrvs05\VS05_VOL11"


REM *** UKSTRVS06 ***

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS06-M$-MacSupport-BAR.xls" "\\ukstrvs06\MacSupport"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS06-M$-Rough_Guides_Digital-BAR.xls" "\\ukstrvs06\Rough Guides Digital"

REM *** UKSTRVS07 ***

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS07-E$-Vol01-BAR.xls" "\\ukstrvs07\VS07_VOL01"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS07-F$-Vol02-BAR.xls" "\\ukstrvs07\VS07_VOL02"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS07-G$-Vol03-BAR.xls" "\\ukstrvs07\VS07_VOL03"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS07-H$-Vol04-BAR.xls" "\\ukstrvs07\VS07_VOL04"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS07-I$-Vol05-BAR.xls" "\\ukstrvs07\VS07_VOL05"

REM *** UKSTRFS04 ***

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\FS04-Q$-BBC-BAR.xls" "\\ukstrfs04\BBC"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\FS04-Q$-Publishing_Management-BAR.xls" "\\ukstrfs04\Publishing Management"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\FS04-Q$-Warne_Resources-BAR.xls" "\\ukstrfs04\Warne Resources"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\FS04-R$-B&L_Resources-BAR.xls" "\\ukstrfs04\B&L Resources"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\FS04-S$-0-8-BAR.xls" "\\ukstrfs04\0-8"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\FS04-S$-Licensing-BAR.xls" "\\ukstrfs04\Licensing"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\FS04-T$-VolA01-BAR.xls" "\\ukstrfs04\VolA01"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\FS04-U$-VolA02-BAR.xls" "\\ukstrfs04\VolA02"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\FS04-V$-VolA03-BAR.xls" "\\ukstrfs04\VolA03"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\FS04-X$-VolA04-BAR.xls" "\\ukstrfs04\VolA04"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\FS04-Y$-VolA05-BAR.xls" "\\ukstrfs04\VolA05"

REM *** PROBLEMATIC SCANS! ***

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /EXCEL "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\Excel\VS05-S$-Vol13-BAR.xls" "\\ukstrvs05\VS05_VOL13"





