"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS01-G$-PUK-BAR.jpg" "\\ukstrvs01\g$\pss programs"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS01-I$-PUK-BAR.jpg" "\\ukstrvs01\PUK DATA8"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS01-J$-PUK-BAR.jpg" "\\ukstrvs01\PUK DATA6"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS01-K$-PUK-BAR.jpg" "\\ukstrvs01\PUK DATA5"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS01-L$-PED_KB-BAR.jpg" "\\ukstrvs01\KNOWLEDGE BOX$"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS01-L$-PSS-BAR.jpg" "\\ukstrvs01\PSS DATA4"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS01-L$-PUK-BAR.jpg" "\\ukstrvs01\PUK DATA7"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS01-M$-PUK-BAR.jpg" "\\ukstrvs01\PUK DATA3$"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS01-M$-GEN_ED2-BAR.jpg" "\\ukstrvs01\GEN ED2$"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS01-M$-PUK_PROGRAMS-BAR.jpg" "\\ukstrvs01\PUK PROGRAMS"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS01-P$-PED-BAR.jpg" "\\ukstrvs01\PED DATA2"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS01-P$-PSS-BAR.jpg" "\\ukstrvs01\PSS DATA2"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS01-P$-PUK-BAR.jpg" "\\ukstrvs01\PUK DATA2"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS01-S$-PUK_DIGITAL_CONTENT-BAR.jpg" "\\ukstrvs01\DIGITAL CONTENT$"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS01-T$-PED_PAS-BAR.jpg" "\\ukstrvs01\PAS DATA"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS01-W$-PUK_MAC-BAR.jpg" "\\ukstrvs01\W$\PUK MAC"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS01-X$-PED_BBCA-BAR.jpg" "\\ukstrvs01\X$\PED DATA"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS01-Y$-PLC-BAR.jpg" "\\ukstrvs01\PLC DATA"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS01-Y$-PUK-BAR.jpg" "\\ukstrvs01\PUK DATA"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS02-PUK_ATOM-BAR.jpg" "\\ukstrvs02\USERSPUKATOM"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS02-PUK_NTOZ-BAR.jpg" "\\ukstrvs02\USERSPUKNTOZ"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS02-NONPUK-BAR.jpg" "\\ukstrvs02\USERSNONPUK"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe" /BARCHART "\\ukstrsal01\serversalive$\VS02-PSSUSERS-BAR.jpg" "\\ukstrvs02\USERSPSS"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS01-G$-PUK-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS01-G$-PUK.xml" "\\ukstrvs01\g$\pss programs"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS01-I$-PUK-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS01-I$-PUK.xml" "\\ukstrvs01\PUK DATA8"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS01-J$-PUK-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS01-J$-PUK.xml" "\\ukstrvs01\PUK DATA6"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS01-K$-PUK-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS01-K$-PUK.xml" "\\ukstrvs01\PUK DATA5"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS01-L$-PED_KB-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS01-K$-PED_KB.xml" "\\ukstrvs01\KNOWLEDGE BOX$"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS01-L$-PSS-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS01-L$-PSS.xml" "\\ukstrvs01\PSS DATA4"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS01-L$-PUK-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS01-L$-PUK.xml" "\\ukstrvs01\PUK DATA7"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS01-M$-PUK-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS01-M$-PUK.xml" "\\ukstrvs01\PUK DATA3$"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS01-M$-GEN_ED2-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS01-M$-PUK_GEN_ED2.xml" "\\ukstrvs01\GEN ED2$"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS01-M$-PUK_PROGRAMS-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS01-M$-PUK_PROGRAMS.xml" "\\ukstrvs01\PUK PROGRAMS"


"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS01-M$-PUK_PROGRAMS-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS01-M$-PUK_PROGRAMS.xml" "\\ukstrvs01\PUK PROGRAMS"


"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS01-P$-PED-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS01-P$-PED.xml" "\\ukstrvs01\PED DATA2"


"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS01-P$-PSS-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS01-P$-PSS.xml" "\\ukstrvs01\PSS DATA2"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS01-P$-PUK-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS01-P$-PUK.xml" "\\ukstrvs01\PUK DATA2"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS01-S$-PUK_DIGITAL_CONTENT-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS01-S$-PUK_DIGITAL_CONTENT.xml" "\\ukstrvs01\DIGITAL CONTENT$"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS01-P$-PUK-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS01-P$-PUK.xml" "\\ukstrvs01\PUK DATA2"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS01-T$-PED_PAS-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS01-T$-PAS.xml" "\\ukstrvs01\PAS DATA"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS01-W$-PUK_MAC-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS01-W$-PUK_MAC.xml" "\\ukstrvs01\W$\PUK MAC"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS01-X$-PED_BBCA-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS01-X$-PED_BBCA.xml" "\\ukstrvs01\X$\PED DATA"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS01-Y$-PLC-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS01-Y$-PLC.xml" "\\ukstrvs01\PLC DATA"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS01-Y$-PUK-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS01-Y$-PUK.xml" "\\ukstrvs01\PUK DATA"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS02-PUK_ATOM-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS02-USERSPUKATOM.xml" "\\ukstrvs02\USERSPUKATOM"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS02-PSS-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS02-USERSPSS.xml" "\\ukstrvs02\USERSPSS"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS02-PUK_ATOM-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS02-USERSPUKATOM.xml" "\\ukstrvs02\USERSPUKATOM"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS02-PUK_NTOZ-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS02-USERSPUKNTOZ.xml" "\\ukstrvs02\USERSPUKNTOZ"

"C:\Program Files\JAM Software\TreeSize Professional\TreeSize.exe"  /SIZEUNIT 3 /HISTORYCHART "\\ukstrsal01\serversalive$\VS02-NONPUK-BAR-history.jpg" /xml "\\ukstrvs01\itshare$\Server Team\!Important Stuff\SAN info\Storage Reports\VS02-USERSNONPUK.xml" "\\ukstrvs02\USERSNONPUK"
























